 name: CI

 on:
   push:
     branches:
       - main
   pull_request:
     branches:
      - main
   workflow_dispatch:

 jobs:
   lint:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the code
         uses: actions/checkout@v2
       - name: Run Lint
         run: echo 'lint' 
       #./gradlew Lint
       # - name: Upload HTML report
       #   uses: actions/upload-artifact@v2
       #   with:
       #       name: lint.html
       #       path: app/build/reports/lint-results-debug.html
   unit-test:
     needs: [lint]
     runs-on: ubuntu-latest
     steps:
       - name: checkout the code
         uses: actions/checkout@v2
       - name: Run tests
         uses: ./gradlew test
       - name: upload the report
         uses: actions/upload-artifact@v2
         with:
            name: unit-test-report
            path: app/build/reports/tests/testDebugUnitTest/
   instrumentation-test:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
       - name: checkout the code
         uses: actions/checkout@v2
       - name: Run tests
         uses: reactivecircus/android-emulator-runner@v2
         with:
          api-level: 29
       - name: upload the report
         uses: actions/upload-artifact@v2
         with:
             name: instrumentation-test-report
             path: app/build/reports/androidTests/connected/

   static-code-analysis:
     needs: [instrumentation-test]
     runs-on: ubuntu-latest
     steps:
       - name: checkout the code
         uses: actions/checkout@v2

       - name: setup JDK
         uses: actions/setup-java@v1
         with:
           java-version: '11'

       - name: Sonar cloud scan
         run: ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }}
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

       - name: upload the report
         uses: actions/upload-artifact@v2
         with:
             name: static-code-analysis-report

   package:
      needs: [static-code-analysis]
      name: Build APK
      runs-on: ubuntu-latest
      steps:
       - name: checkout the code
         uses: actions/checkout@v2

       - name: setup JDK 1.8
         uses: actions/setup-java@v1
         with:
           java-version: 1.8

       - name: Build the app
         run: ./gradlew assembleDebug --stacktrace

       - name: upload the apk
         uses: actions/upload-artifact@v2
         with:
             name: app.apk
             path: app/build/outputs/apk/debug/app-debug.apk





              
